services:
  nginx:
    image: nginx:alpine
    container_name: iso_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - iso_net

  php:
    build:
      context: ./docker/php
    container_name: iso_php
    volumes:
      - ./:/var/www/html
    networks:
      - iso_net

  db:
    image: mariadb:10.11
    container_name: iso_db
    environment:
      MYSQL_DATABASE: iso_platform
      MYSQL_USER: iso_user
      MYSQL_PASSWORD: iso_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - iso_net

networks:
  iso_net:

volumes:
  db_data:
